# Generated by Django 5.2 on 2025-04-21 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='habit',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekly_progress',
            field=models.JSONField(default=list),
        ),
    ]
